name: sentinel

services:
  database:
    image: gvenzl/oracle-free:latest
    container_name: sentinel_database

    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}

    ports:
      - "1521:1521"

    volumes:
      - oracle_data:/opt/oracle/oradata

    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s

    restart: unless-stopped

  api:
    build:
      context: ../../app/target-api
      dockerfile: Dockerfile

    container_name: sentinel_api

    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//database:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: ${APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_USER_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      database:
        condition: service_healthy

    restart: unless-stopped

volumes:
  oracle_data:
