name: sentinel

services:
  database:
    image: gvenzl/oracle-free:23.26.3
    container_name: sentinel_database

    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${DB_USERNAME}
      APP_USER_PASSWORD: ${DB_PASSWORD}

    ports:
      - "1521:1521"

    volumes:
      - oracle_data:/opt/oracle/oradata

    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s

    restart: unless-stopped

  api:
    build:
      context: ../../app/target-api
      dockerfile: Dockerfile

    container_name: sentinel_api

    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//database:1521/FREEPDB1
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      database:
        condition: service_healthy

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.13.4
    container_name: sentinel_prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    depends_on:
    - api

    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.2.3
    container_name: sentinel_grafana

    ports:
      - "3000:3000"
    
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning:ro
    - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus

    restart: unless-stopped

volumes:
  oracle_data:
  grafana_data:
