apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "oracle.fullname" . }}
  labels:
    {{- include "oracle.labels" . | nindent 4 }}

spec:
  serviceName: {{ include "oracle.fullname" . }}
  replicas: 1

  selector:
    matchLabels:
      {{- include "oracle.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "oracle.selectorLabels" . | nindent 8 }}

    spec:
      nodeSelector:
        node-role: workload

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: oracle
              containerPort: {{ .Values.container.port }}
              protocol: TCP

          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: oracle-password

            - name: APP_USER
              value: {{ .Values.oracle.appUser | quote }}

            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: app-user-password

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata

  volumeClaimTemplates:
    - metadata:
        name: oracle-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.storage.size }}